name: Deploy to Production
on: 
  push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [v16.x]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_REACT_APP_USER_MAKERDAO_NETWORK_API: ${{ secrets.REACT_APP_USER_MAKERDAO_NETWORK_API }}
          envkey_REACT_APP_PASSWORD_MAKERDAO_NETWORK_API: ${{ secrets.REACT_APP_PASSWORD_MAKERDAO_NETWORK_API }}
          file_name: .env
          fail_on_empty: true
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build # will run `yarn build` command
      - name: Copy file via scp
        uses: appleboy/scp-action@master
        with:
          source: "build/*,build/.env"
          target: "/var/www/production"
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          overwrite: true
